# Generated by Django 4.2.4 on 2023-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otplogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpprovidor',
            name='providor',
            field=models.CharField(choices=[('SSLWireless', 'SSLWireless'), ('MIMSMS', 'MIMSMS'), ('Twilio', 'Twilio')], max_length=12),
        ),
    ]
